### ISSUE TITLE
Copyright infringement.

### ISSUE THREAD

**Issue by ProjectInfinity** [jasonwynn10/EnderEye-TP#1]
Please remove all infringing code, signs of infringement impending and future plans of infringement as seen here:
https://github.com/jasonwynn10/EnderEye-TP/blob/master/src/TP/Main.php
https://github.com/jasonwynn10/EnderEye-TP/commit/95d416fbe67a5f00fb038e43f11775c1a937bb05

Our projects are not open source and you are not free to distribute any of the code as your own. Failure to comply will result in a DMCA takedown.

You have 48 hours, thank you.

**Comment by jasonwynn10** [comment]
resolved, I hope
